/* ac2ffaa54ec28711592e538175ec64ca265abc18
 * This file is automatically generated by graphql-let. */

import * as Types from "graphql-let/__generated__/__types__";
export declare type PartialFragment = ({
  __typename?: 'User';
} & Pick<Types.User, 'id' | 'name'>);
export declare const PartialFragmentDoc: import("@apollo/client").DocumentNode;